image: node:15.12-alpine3.13

stages:
  - test
  - deploy

test:
  stage: test
  script:
  - yarn install
  - yarn build
  except:
    - master

pages:
  stage: deploy
  script:
  - yarn install
  - yarn build
  - mv ./build ./public
  artifacts:
    paths:
    - public
  only:
    - master
  # 设置环境变量
  environment:
    name: production
    url: https://192.168.3.249:8081/ceoifung/library/public
  # 设置环境变量
  variables:
    CI: true
    GITLAB_CI: true
